#!/usr/bin/env python3
"""
report_finetune.py -- the Whisper fine-tuning TRAINING LOG.

Rebuilds results/c1_asr_finetune_report.md from every
results/c1_asr_finetune_<run>.json, newest run first in the log table, one
section per run. finetune_whisper.py calls this automatically at the end of
every training run, so the log never falls behind; it can also be run by hand:

    python report_finetune.py

Human context for a run (why it was run, what changed) lives in RUN_NOTES
below for older runs, and in the "note" field written by
`finetune_whisper.py --note "..."` for new ones.

Each epoch is scored by validation LOSS during training; WER is measured once
per run, on the best-epoch adapter (the only one saved).
"""
import glob
import json
import os
from datetime import datetime

C1_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS_DIR = os.path.join(C1_ROOT, "results")
MODEL_DIR = os.path.join(C1_ROOT, "models", "whisper_lora")
OUT = os.path.join(RESULTS_DIR, "c1_asr_finetune_report.md")

# Context for runs made before finetune_whisper.py recorded a --note.
RUN_NOTES = {
    "small": "First run. Original training data (1.59 h). 18 training transcripts "
             "were silently truncated at 440 tokens (found later).",
    "medium": "First run, same data as `small`.",
    "large-v3": "First run, same data as `small`.",
    "small_lr3e-4": "Experiment: learning rate 3e-4 instead of 1e-3, up to 15 epochs, "
                    "patience 3. Same data as `small`. Longer training did not help "
                    "(still peaked at epoch 4) but output looped less.",
    "small_v2": "Added the label-only exclusions, re-timed recordings, R0062-R0065 and "
                "split long utterances (2.70 h). WORSE: 37 transcripts truncated at 440 "
                "tokens taught the model not to stop -> heavy looping.",
    "small_v3": "Same data as v2 with every training transcript capped at 400 tokens "
                "(dense clips split, none truncated). Confirmed truncation caused the "
                "v2 looping.",
    "small_v4": "Current data (3.09 h, adds R0066-R0067 and R0076-R0080). Same data and "
                "settings as medium_v4 / large-v3_v4.",
    "medium_v4": "Current data (3.09 h), token-capped transcripts.",
    "large-v3_v4": "Current data (3.09 h), token-capped transcripts.",
}


def load_runs():
    runs = []
    for path in glob.glob(os.path.join(RESULTS_DIR, "c1_asr_finetune_*.json")):
        with open(path, encoding="utf-8") as fh:
            r = json.load(fh)
        r["_run"] = r.get("run") or r["model"]
        r["_file"] = os.path.basename(path)
        r["_complete"] = "finetuned_test" in r
        if r["_file"].endswith("_interrupted.json"):
            r["_run"] += " (interrupted)"
            r["_complete"] = False
        fin = r.get("finished") or datetime.fromtimestamp(os.path.getmtime(path)).isoformat(timespec="minutes")
        r["_finished"] = fin
        runs.append(r)
    runs.sort(key=lambda r: r["_finished"])
    return runs


def load_rescores():
    out = {}
    for path in glob.glob(os.path.join(RESULTS_DIR, "c1_asr_rescore_*.json")):
        with open(path, encoding="utf-8") as fh:
            r = json.load(fh)
        out[r["run"]] = r
    return out


def best_val(r):
    b = r.get("best_epoch")
    return next((c["val_loss"] for c in r.get("curve", []) if c["epoch"] == b), None)


def fmt(x, nd=3):
    return "—" if x is None else f"{x:.{nd}f}"


def test_n(r):
    return r.get("data", {}).get("test", {}).get("n_clips")


def epoch_table(r):
    curve, best = r.get("curve", []), r.get("best_epoch")
    L = ["| epoch | train loss | val loss | change | val − train | epoch time | |\n",
         "|---|---|---|---|---|---|---|\n"]
    prev_v, prev_t = None, 0.0
    for c in curve:
        e, vl, tl, t = c["epoch"], c["val_loss"], c.get("train_loss"), c.get("elapsed_min")
        mark = ("before training" if e == 0 else "**best — saved**" if e == best
                else "val worse" if prev_v is not None and vl > prev_v else "")
        L.append(f"| {e} | {fmt(tl, 4)} | {'**' if e == best else ''}{vl:.4f}"
                 f"{'**' if e == best else ''} | "
                 f"{'—' if prev_v is None else f'{vl - prev_v:+.4f}'} | "
                 f"{'—' if tl is None else f'{vl - tl:+.3f}'} | "
                 f"{'—' if t is None else f'{t - prev_t:.1f} min'} | {mark} |\n")
        prev_v = vl
        if t is not None:
            prev_t = t
    return L


def main():
    runs = load_runs()
    rescores = load_rescores()
    done = [r for r in runs if r["_complete"]]

    L = ["# Whisper fine-tuning — training log\n\n",
         f"_Auto-generated by `scripts/report_finetune.py`; last updated "
         f"{datetime.now().strftime('%Y-%m-%d %H:%M')}. Every training run updates this "
         f"file. Do not edit by hand: add context with `finetune_whisper.py --note`._\n\n",
         "**Method (all runs):** LoRA on attention + feed-forward layers, base weights "
         "frozen in bf16, language token `en`, effective batch 16 clips, linear warm-up "
         "then decay, early stopping on validation loss. Data is split by recording; "
         "validation (6 recordings) and test (10 recordings) are fixed so runs stay "
         "comparable. Scores are script-normalised (Sinhala Unicode vs romanized is not "
         "penalised), greedy decoding.\n\n"]

    # --- log table -------------------------------------------------------------
    L.append("## Run log (newest first)\n\n")
    L.append("| finished | run | train data | lr | best epoch | best val loss "
             "| test clips | WER | words recovered | extra words | train time |\n")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|\n")
    for r in reversed(runs):
        s = r.get("finetuned_test") or {}
        d = r.get("data", {}).get("train", {})
        recov = f"{100 * s['recall_of_ref_words']:.1f}%" if s else "—"
        extra = f"{s['insertions']:,}" if s else "—"
        mins = f"{r['train_minutes']:.0f} min" if r.get("train_minutes") else "—"
        L.append(f"| {r['_finished'].replace('T', ' ')} | `{r['_run']}` "
                 f"| {d.get('hours', 0):.2f} h / {d.get('n_recordings', '?')} rec "
                 f"| {r.get('lr')} | {r.get('best_epoch', '—')} | {fmt(best_val(r))} "
                 f"| {test_n(r) or '—'} | {fmt(s.get('norm_wer'))} | {recov} | {extra} "
                 f"| {mins} |\n")
    L.append("\nWER from runs with different test-clip counts (101 vs 111) is not "
             "directly comparable; see the leaderboard for one common test set.\n\n")

    # --- leaderboard on the current test set ---------------------------------------
    cur_n = max((test_n(r) or 0) for r in done) if done else 0
    board = []
    for r in done:
        if test_n(r) == cur_n:
            board.append((r["_run"], r["finetuned_test"], r))
    for run, rs in rescores.items():
        if rs.get("test_split", {}).get("n_clips") == cur_n:
            board.append((f"{run} (re-scored)", rs["finetuned_test"], None))
    board.sort(key=lambda x: x[1]["norm_wer"])
    L.append(f"## Leaderboard — current test set ({cur_n} clips)\n\n")
    L.append("| rank | run | WER | char. error rate | words recovered | output ÷ ref "
             "| extra words |\n|---|---|---|---|---|---|---|\n")
    for i, (run, s, _) in enumerate(board, 1):
        b = "**" if i == 1 else ""
        L.append(f"| {i} | {b}`{run}`{b} | {b}{s['norm_wer']:.3f}{b} | {s['norm_cer']:.3f} "
                 f"| {100 * s['recall_of_ref_words']:.1f}% | {s['output_ratio']:.2f}× "
                 f"| {s['insertions']:,} |\n")
    bases = {}
    for r in done:
        if test_n(r) == cur_n and "baseline_test" in r:
            bases[r["model"]] = r["baseline_test"]
    if bases:
        L.append("\nOff-the-shelf on the same test set: " + "; ".join(
            f"`{m}` WER {b['norm_wer']:.3f} ({100 * b['recall_of_ref_words']:.1f}% recovered)"
            for m, b in sorted(bases.items())) + ".\n")
    L.append("\n")

    # --- decoding experiment: loop safeguards (safeguard_decode.py) ------------
    sg = []
    for path in sorted(glob.glob(os.path.join(RESULTS_DIR, "c1_asr_safeguard_*.json"))):
        with open(path, encoding="utf-8") as fh:
            sg.append(json.load(fh))
    if sg:
        sg.sort(key=lambda d: d["safeguard_test"]["norm_wer"])
        L.append("## Decoding experiment — loop safeguards\n\n")
        L.append("Same trained adapters, re-scored by `scripts/safeguard_decode.py`. A clip "
                 "counts as looping only if its output is more repetitive than any gold "
                 "transcript (compression ratio > 3.0, a word repeated > 10 times or a "
                 "phrase > 5 times in a row, or > 10 words per second); those clips are "
                 "re-decoded with 5-beam search, and truncated at the repetition if still "
                 "looping. Every other clip is left exactly as greedy decoding produced "
                 "it; no gold transcript trips the thresholds. All 111 test clips are "
                 "scored either way.\n\n")
        L.append("| run | looping clips | WER greedy → safeguarded | char. error rate "
                 "| words recovered | extra words | missed words |\n"
                 "|---|---|---|---|---|---|---|\n")
        for i, d in enumerate(sg):
            g, s = d["greedy_test"], d["safeguard_test"]
            b = "**" if i == 0 else ""
            L.append(f"| {b}`{d['run']}`{b} | {d['n_flagged']}/{d['n_clips']} "
                     f"| {g['norm_wer']:.3f} → {b}{s['norm_wer']:.3f}{b} "
                     f"| {g['norm_cer']:.3f} → {s['norm_cer']:.3f} "
                     f"| {100 * g['recall_of_ref_words']:.1f}% → "
                     f"{100 * s['recall_of_ref_words']:.1f}% "
                     f"| {g['insertions']:,} → {s['insertions']:,} "
                     f"| {g['deletions']:,} → {s['deletions']:,} |\n")
        L.append("\n")

    # --- per-run detail (newest first) -------------------------------------------
    L.append("## Runs in detail (newest first)\n\n")
    for r in reversed(runs):
        L.append(f"### `{r['_run']}` — finished {r['_finished'].replace('T', ' ')}\n\n")
        note = r.get("note") or RUN_NOTES.get(r.get("run") or r["model"])
        if note:
            L.append(f"{note}\n\n")
        d = r.get("data", {})
        tr = d.get("train", {})
        L.append(f"- Model `{r['model']}`, lr {r.get('lr')}, LoRA rank {r.get('lora_r')}, "
                 f"max {r.get('epochs_max', 10)} epochs, patience {r.get('patience', 2)}, "
                 f"seed {r.get('seed')}.\n")
        L.append(f"- Train {tr.get('n_recordings', '?')} recordings / {tr.get('n_clips', '?')} "
                 f"clips / {tr.get('hours', 0):.2f} h; test {test_n(r) or '?'} clips.\n")
        if not r["_complete"]:
            L.append("- **Incomplete** — stopped before test scoring.\n\n")
        else:
            s, b = r["finetuned_test"], r.get("baseline_test")
            if b:
                L.append(f"- Off-the-shelf → fine-tuned: WER {b['norm_wer']:.3f} → "
                         f"**{s['norm_wer']:.3f}**, words recovered "
                         f"{100 * b['recall_of_ref_words']:.1f}% → "
                         f"**{100 * s['recall_of_ref_words']:.1f}%**, extra words "
                         f"{b['insertions']:,} → {s['insertions']:,}.\n")
            else:
                L.append(f"- Fine-tuned: WER **{s['norm_wer']:.3f}**, words recovered "
                         f"**{100 * s['recall_of_ref_words']:.1f}%**, extra words "
                         f"{s['insertions']:,}.\n")
            L.append(f"- Best epoch {r.get('best_epoch')} (val loss {fmt(best_val(r), 4)}); "
                     f"{fmt(r.get('train_minutes'), 0)} min training; peak GPU "
                     f"{fmt(r.get('peak_gpu_gib'), 1)} GiB.\n")
            rs = rescores.get(r.get("run") or r["model"])
            if rs:
                t = rs["finetuned_test"]
                L.append(f"- Re-scored on the {rs['test_split']['n_clips']}-clip test set: "
                         f"WER {t['norm_wer']:.3f}, words recovered "
                         f"{100 * t['recall_of_ref_words']:.1f}%.\n")
        L.append("\n")
        if r.get("curve"):
            L.extend(epoch_table(r))
            L.append("\n")

    L.append("## Reading the log\n\n")
    L.append("- **Validation loss** picks the epoch within a run; it always feeds the "
             "model the correct previous words, so it cannot see repetition loops. "
             "**Test WER / words recovered / extra words** rank runs.\n")
    L.append("- One training run per configuration and a 10-recording test set: "
             "differences of a few points are within noise.\n")
    L.append("- Predictions for each run (with these fine-tuning details at the end) "
             "are in `predictions/finetune/<run>_{base,ft}_test.json`.\n")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.writelines(L)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
